### ISSUE TITLE
Last Washington Post Crossword Issue

### ISSUE THREAD

**Issue by johnroven** [thisisparker/xword-dl#102]
On March 5th, WP uploaded a new crossword that includes black squares with letters in them. It causes issues. For example, for a clue "22 Eldest daughter on "The Brady Bunch"", it provides answer "MARCIALONE" insead of "MARC" or "MARCIA".

**Comment by thisisparker** [comment]
Cool puzzle! Seeing as it uses features that the .puz file format doesn't support, this is something that xword-dl can't and won't be able to handle. There are some instances where an unusual puzzle highlights some default behavior that xword-dl should do differently, but I don't think this is one of those.
