### ISSUE TITLE
Circles not parsed by CrosswordCompiler Downloader

### ISSUE THREAD

**Issue by thisisparker** [thisisparker/xword-dl#103]
E.g. the 3/18/23 Modern Crossword has circles that are not encoded into the resulting .puz

**Comment by boisvert42** [comment]
I just opened a PR for this

**Comment by thisisparker** [comment]
Wow, awesome, thank you! I definitely had just opened this issue to remind myself to fix it, but this is even better :)

I've got a few open PRs that I think are just about ready to merge, so I'll cut a release soon and make sure this is in there. Thanks again!

**Comment by boisvert42** [comment]
I don't think this violates my blood oath not to work on puz files anymore

**Comment by thisisparker** [comment]
Closed by #104, now shipped
