### ISSUE TITLE
RFE: newyorker: extract title (theme) from Friday crosswords

### ISSUE THREAD

**Issue by edsantiago** [thisisparker/xword-dl#111]
Friday New Yorker crosswords are themed. I just happened to notice that  [today's](https://www.newyorker.com/puzzles-and-games-dept/crossword/2023/06/30) includes a subheading _Today's theme: Genre studies._ It looks like all Fridays have a _Today's theme: XX_ subheading. Would that be easy to detect and set as / append to puzzle title?

Thank you!

**Comment by thisisparker** [comment]
I have a sense I had previously considered this and decided that it's not a "title," but looking at it now I think I agree with you. I do try to be minimally destructive with changes to copy, but maybe the theme title (if present) could replace "The Crossword" as the thing before the colon and date? I don't want to remove the date from the title

**Comment by edsantiago** [comment]
Title can be pretty long, e.g. (from today's A.V. club): _June 30, 2023 - "Twisted Logic" (themeless) - Kunal Nabar, edited by Max Carpenter_. I think think appending colon+theme would be safe.
