### ISSUE TITLE
Support for New Yorker cryptic

### ISSUE THREAD

**Issue by danderson** [thisisparker/xword-dl#137]
The New Yorker publishes a cryptic on Sundays: https://www.newyorker.com/tag/cryptic-crossword . Hopefully it's the same platform as the quick crossword that's already supported!

**Comment by thisisparker** [comment]
Alas, closing this one for [the worst reason](https://www.newyorker.com/puzzles-and-games-dept/articles/introducing-the-new-yorker-mini-crossword)

> We’ll no longer publish a cryptic crossword on Sundays, but fans of the form can still access our [archive](https://www.newyorker.com/puzzles-and-games-dept/cryptic-crossword) of more than two hundred cryptics.

I loved that cryptic! I hope it returns!
