### ISSUE TITLE
Unable to download The Guardian Daily Quick crossword

### ISSUE THREAD

**Issue by yang-musa** [thisisparker/xword-dl#190]
System: Fedora 40 Gnome, up to date as of today (May 31, 2024).
Crosswords 0.3.13.2 installed via Flatpak.

Error:
For the past week, clicking to download The Guardian Daily Quick crossword gives the error "Problem downloading puzzle. Unable to download a puzzle from "The Guardian Daily Quick Crossword"

Expected behavior:
Crossword should download like it used to.

I ran flatpak run org.gnome.Crosswords in the terminal and got the following:

```
Traceback (most recent call last):
  File "/app/extensions/xword-dl/bin/xword-dl.orig", line 33, in <module>
    sys.exit(load_entry_point('xword-dl==2023.12.2', 'console_scripts', 'xword-dl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/extensions/xword-dl/lib/python3.11/site-packages/xword_dl-2023.12.2-py3.11.egg/xword_dl/xword_dl.py", line 257, in main
    puzzle, filename = by_keyword(args.source, **options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/extensions/xword-dl/lib/python3.11/site-packages/xword_dl-2023.12.2-py3.11.egg/xword_dl/xword_dl.py", line 37, in by_keyword
    puzzle_url = dl.find_latest()
                 ^^^^^^^^^^^^^^^^
  File "/app/extensions/xword-dl/lib/python3.11/site-packages/xword_dl-2023.12.2-py3.11.egg/xword_dl/downloader/guardiandownloader.py", line 25, in find_latest
    url = soup.find('a', attrs={'data-link-name': 'article'}).get('href')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

Hope that's helpful in tracing the error. Let me know if any additional information is needed.

(I [originally filed this with the Crosswords app](https://gitlab.gnome.org/jrb/crosswords/-/issues/220), but they believe the error lies in the xwords component).

**Comment by mixographer** [comment]
Today I also see that all the Guardian puzzles fail in a similar fashion.

**Comment by thisisparker** [comment]
Oh good, that should be more easily fixable. I've got a backlog of `xword-dl` work right now but I'm hoping to find a few hours this week to fix this and a few other outstanding issues and cut a new release!

Thanks for reporting, @yang-musa!

**Comment by mixographer** [comment]
I tried to fix it, but I need to figure out Beautiful Soup again....
