### ISSUE TITLE
Is Wapo broken. I seem to get the same puzzle every day

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#33]
Washington Post is broken for me. i seem to get the same puzzle 20210905 every time

**Comment by thisisparker** [comment]
Washington Post is a weekly puzzle, so expected behavior would be the same puzzle between Sundays

**Comment by mixographer** [comment]
Ahhh. I just pulled up this page 'https://www.washingtonpost.com/crossword-puzzles/daily/', and had thought maybe they were daily. I understand. Thanks!
