### ISSUE TITLE
Daily Beast dropped the date in the title? 

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#36]
I saw db broke today and when I looked at the puzzleme on the site today's puzzle doesn't have the date. 

Then I noticed this comment:
"      # Daily Beast puzzle IDs, unusually for AmuseLabs puzzles, don't include
        # the date. This pulls it out of the puzzle title, which will work
        # as long as that stays consistent."

I'm not familiar yet with the format, so I don't have a PR, but I thought I'd let you know. maybe tomorrow they'll add today's date to the current puzzle, and only not date the current puzzles.

**Comment by mixographer** [comment]
Fix works. I'll close this. thanks!!

**Comment by thisisparker** [comment]
It seems the date is added manually, and so every once in a while there are some inconsistencies. Yesterday's puzzle was the first I'd seen without a date at all but I suspect that was just a one-off blip. In any case, this change reflects the desired behavior better: if it can pull the date from the title that's great, and if not don't sweat it.

(BTW, I made this change before seeing your issue! Didn't want you to think I was ignoring you, and thank you for opening it.)
