### ISSUE TITLE
error fetching several puzzle sources: invalid start byte

### ISSUE THREAD

**Issue by EG-tech** [thisisparker/xword-dl#47]
Hi, I have recently started receiving an error when trying to use `xword-dl` to fetch New Yorker's puzzles:

``'utf-8' codec can't decode byte 0x9b in position 1: invalid start byte``

This is on Ubuntu 20.04.04, Python 3.8.10 and the latest xword-dl 2022.05.21 - all the other outlets/shortcodes seem fine! I'm not sure exactly how far back this started, probably a week or two. Thank you for this wonderful tool :smile:

**Comment by edsantiago** [comment]
>latest xword-dl 2022.05.21

Latest is `2022.6.20`. The issue you report was fixed by #46.

**Comment by EG-tech** [comment]
My mistake! Thank you!
