### ISSUE TITLE
Confusing error for NYT puzzles if authentication is not current

### ISSUE THREAD

**Issue by thisisparker** [thisisparker/xword-dl#56]
It should either catch that the returned json has no `puzzle_data` or that the `entitlement` is `basic` and not `premium`, and prompt the user to re-authenticate. As it stands, it raises a KeyError which was confusing to me and also led to #55.

**Comment by thisisparker** [comment]
This should be closed with f58f16b997cdfd1b078f6eb75ab4fd12d2f1fe86. I'll close the issue when I ship a new release!

**Comment by mixographer** [comment]
Thanks for tracking this.
