### ISSUE TITLE
Guardian 'no solution provided' question. 

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#72]
If I grab the puzzle at 'https://www.theguardian.com/crosswords/everyman/3969'

I get this message:
Puzzle downloaded and saved as Guardian - 20221105 - Everyman crossword No 3,969 - no solution provided.puz.

and the file is named with the 'no solution...' naming convention, 

but the solution is provided and saved in the .puz file. something changes in the json when they add the solutions after the initial publication. I'll take a look and see if I can provide more details.

**Comment by mixographer** [comment]
interesting. I see that the puzzle I listed still has 'solutionAvailable = false' even though the solution is available. 

`{"x":​12,"y":​11}​,"separatorLocations":​{}​,"solution":​"STAR"}​,{"id":
​"22-down","number":​22,"humanNumber":​"22","clue":​"The French rehashed
gutted calorific ingredient
(4)​","direction":​"down","length":​4,"group":​["22-down"]​,"position":​
{"x":​14,"y":​11}​,"separatorLocations":​{}​,"solution":​"LARD"}​]​,"
solutionAvailable":​false,"dateSolutionAvailable":​1668297600000,"
dimensions":​{"cols":​15,"rows":​15}​,"crosswordType":​"everyman","pdf":
​"https:​/​/​crosswords-static.guim.co.uk/​obs.everyman.20221106.pdf"}​"`

**Comment by mixographer** [comment]
I looked back at other puzzles, and it seems like 'solutionAvailable' is a flag of whether the solution was published when the puzzle went live. One thing to do is maybe look and see if something like 

`int(round(time.time() * 1000))`

is after 'dateSolutionAvailable'

but then you add another dependency for 'Time.'

**Comment by thisisparker** [comment]
`time` is part of the standard library so an import is cheap. But that's a good catch! I did assume that solutionAvailable would be changed when, well, the solution is available.

I think probably a still-better approach would be to just check to see whether the solution is available :). I'll update that in the next release.

**Comment by mixographer** [comment]
ok, I wrote the code to check if the solution date has passed. 

I can make a pull if you want it but really just: 

`puzzle.solution_seconds = xword_data.get('dateSolutionAvailable')
        current_seconds = int(round(time.time() * 1000))

if (puzzle.solution_seconds > current_seconds):
            puzzle.title += ' -no solution provided'
`

but I'm not great at python.

**Comment by thisisparker** [comment]
Sorry, we were both writing out our approaches at the same time! I think https://github.com/thisisparker/xword-dl/commit/76ac66e62c1b6d04137e8f1d89e3ea2a69aff22f will work and keeps the logic a little tighter

**Comment by mixographer** [comment]
oh, sorry. I'm also not great at github. did forking, and creating a pull in my repo also send it here?

**Comment by mixographer** [comment]
I think this one can be closed.

**Comment by thisisparker** [comment]
Closed with the 2022.11.29 release! :tada:
