### ISSUE TITLE
Naming consistency, download by url (Guardian)

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#74]
I was wondering if the naming convention inconsistency is intentional. For instance if I download the latest Quiptic i might get the file named:
xword-dl % xword-dl grdu
Puzzle downloaded and saved as Guardian Quiptic - 20221113 - Quiptic crossword No 1,200.puz.

while if I download by url:
xword-dl % xword-dl 'https://www.theguardian.com/crosswords/quiptic/1200'
Puzzle downloaded and saved as Guardian - 20221113 - Quiptic crossword No 1,200.puz.

I realize this is in the xword-dl.py and not in the downloader, so maybe it is intentional and the end-user should set up tokens to name the file the way they like?

**Comment by thisisparker** [comment]
Closed with the 2022.11.29 release! :tada:
