### ISSUE TITLE
USA Today and Universal seem to be changing their format. 

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#78]
Universal seems to be down for maintenance the last few days, and USA Today seems to have changed their format. I haven't had a chance to look into it yet, but I thought I'd note it here.

**Comment by thisisparker** [comment]
I think they had a genuine long-lasting outage, but that they're back.

**Comment by thisisparker** [comment]
Oh wow, it looks like it [affected all of Andrews McMeel Syndication](https://twitter.com/AndrewsMcMeel/status/1594478229703753729)... not just crosswords but a bunch of comics and other stuff. Huh!

**Comment by mixographer** [comment]
Yes, it's back. Thanks.
