### ISSUE TITLE
Problems with AmuseLabs and PuzzleMe puzzles? New obfuscation? 

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#81]
I seem to be having issues with PuzzleMe and AmuseLab Puzzles. It's probably something I've changed on my end, but maybe not. 

I'm trying to get these by URL, but I cannot. 
https://joeadultman.blogspot.com/2022/11/bangers-and-mash.html
https://mpcryptics.blogspot.com/2022/12/advent-4.html

I get:
`File "/usr/local/lib/python3.7/site-packages/xword_dl-2022.11.29-py3.7.egg/xword_dl/downloader/amuselabsdownloader.py", line 124, in fetch_data
    xword_data = load_rawc(rawc, amuseKey=amuseKey)
  File "/usr/local/lib/python3.7/site-packages/xword_dl-2022.11.29-py3.7.egg/xword_dl/downloader/amuselabsdownloader.py", line 122, in load_rawc
    return json.loads(base64.b64decode(amuse_b64(rawc, amuseKey)).decode("utf-8"))
  File "/usr/local/lib/python3.7/site-packages/xword_dl-2022.11.29-py3.7.egg/xword_dl/downloader/amuselabsdownloader.py", line 115, in amuse_b64
    while F<len(H):J=H[F];K=int(J,16);E.append(K);F+=1
TypeError: object of type 'NoneType' has no len()
`

**Comment by thisisparker** [comment]
Yeah, this is known and I think I will be shipping a fix today!

**Comment by mixographer** [comment]
wowza! Thanks!

**Comment by thisisparker** [comment]
Closed with new release!
