### ISSUE TITLE
WSJ new Json format from 1/18/23? 

### ISSUE THREAD

**Issue by mixographer** [thisisparker/xword-dl#93]
I'm wondering if WSJ changed their format. I'm getting JSON errors on any WSJ puzzle now. (although I did break my python environment pretty badly yesterday, so it could be me.)

**Comment by thisisparker** [comment]
Close: they changed their URL structure a little bit, so `xword-dl` is grabbing an empty file and throwing a JSON error. I've got a fix in the `dev` branch (which you can install right now if you like), and I'll be shipping a release very shortly.

**Comment by mixographer** [comment]
Thanks. I see the fix.

**Comment by thisisparker** [comment]
Looks like they (at least temporarily) switched back to the old URL format. A new release today accommodates both styles!
