### ISSUE TITLE
NYT Unable to authenticate with NYT servers + Can't find xword-dl.yaml

### ISSUE THREAD

**Issue by Ugleh** [thisisparker/xword-dl#99]
I get the above error when trying to log in, I try it use the token as advised but In Windows, I am in my site-packages folder `C:\Python310\Lib\site-packages` and in xword_dl I can't find any config folder or yaml file.

**Comment by Ugleh** [comment]
It was located in my user folder, which I guess is what is translated as ~ for linux.

**Comment by thisisparker** [comment]
I was just reading up on where Python expands `~` to for Windows. If that doesn't seem like a good place for it, let me know!
